worker-threads: 4
worker-fs-threads: 2
worker-grpc-threads: 2

is_testing: false

testsuite-enabled: false

server-port: 8080
server-grpc-port: 8081

order-endpoint: '[::1]:8081'

dbconnection-postgres: 'postgresql://user:password@172.17.0.1:54321/test_db'